### ISSUE TITLE
【演習 2) タスク 5】リソース グループ IAM 設定のスクリーンショット

### ISSUE THREAD

**Issue by horihiro** [horihiro/containers-cicd-handson-tutorial#33]
https://github.com/horihiro/containers-cicd-handson-tutorial/blob/main/steps/P2-05.md

手順 1-iii. ( `演習 2 の[準備作業](https://github.com/horihiro/containers-cicd-handson-tutorial/blob/main/steps/P2-00.md)で作成されていた Azure リソースグループに対して Azure AD アプリの IAM を 共同作成者 権限で設定します。`) のスクリーンショットが、設定方法ではなく設定結果になっている。
![image](https://user-images.githubusercontent.com/4566555/188061731-e721a2a5-380a-4062-905f-36154433a053.png)

設定方法がわかるスクリーンショットが適切。

**Comment by k-in** [comment]
設定方法がわかるスクリーンショットを追記しました。
ご確認お願いします。

**Comment by horihiro** [comment]
LGTM!
