### ISSUE TITLE
【事前準備】Invalid link of Readmeへ

### ISSUE THREAD

**Issue by joyoji** [horihiro/containers-cicd-handson-tutorial#38]
Where: 
    https://github.com/horihiro/containers-cicd-handson-tutorial/blob/main/steps/Common.md

What:
    Wrong: https://github.com/horihiro/containers-cicd-handson-tutorial/blob/main/steps/README.md
    Correct: https://github.com/horihiro/containers-cicd-handson-tutorial/blob/main/README.md (remove /steps)

How:
    Replace among multiple pages.

**Comment by joyoji** [comment]
I can fix this later.

**Comment by horihiro** [comment]
Fixed by https://github.com/horihiro/containers-cicd-handson-tutorial/pull/43
